<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-22T02:17:57 EET" name="Suite" finished-at="2025-04-22T02:18:46 EET" duration-ms="49367">
    <groups>
    </groups>
    <test started-at="2025-04-22T02:17:57 EET" name="Error Validations Test" finished-at="2025-04-22T02:18:21 EET" duration-ms="24105">
      <class name="tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.ErrorValidationsTest@34cdeda2]" started-at="2025-04-22T02:17:57 EET" name="launchApplication" finished-at="2025-04-22T02:18:14 EET" duration-ms="17323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@34cdeda2]" started-at="2025-04-22T02:18:14 EET" name="LoginErrorValidation" finished-at="2025-04-22T02:18:18 EET" duration-ms="3829" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your email or password is incorrect!] but found [Your email or password is inc orrect!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your email or password is incorrect!] but found [Your email or password is inc orrect!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:tests.ErrorValidationsTest@34cdeda2]" started-at="2025-04-22T02:18:18 EET" name="LoginErrorValidation" finished-at="2025-04-22T02:18:21 EET" duration-ms="2346" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your email or password is incorrect!] but found [Your email or password is inc orrect!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your email or password is incorrect!] but found [Your email or password is inc orrect!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.ErrorValidationsTest@34cdeda2]" started-at="2025-04-22T02:18:21 EET" name="tearDown" finished-at="2025-04-22T02:18:21 EET" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
    <test started-at="2025-04-22T02:17:57 EET" name="Test" finished-at="2025-04-22T02:18:46 EET" duration-ms="49367">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:tests.LoginTest@495b0487]" started-at="2025-04-22T02:17:57 EET" name="launchApplication" finished-at="2025-04-22T02:18:16 EET" duration-ms="18705" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="RegisteredUserCanLogin()[pri:0, instance:tests.LoginTest@495b0487]" started-at="2025-04-22T02:18:16 EET" name="RegisteredUserCanLogin" finished-at="2025-04-22T02:18:25 EET" duration-ms="9065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisteredUserCanLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@495b0487]" started-at="2025-04-22T02:18:46 EET" name="tearDown" finished-at="2025-04-22T02:18:46 EET" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.SubmitOrderTest">
        <test-method signature="submitOrder()[pri:0, instance:tests.SubmitOrderTest@4b6690c0]" started-at="2025-04-22T02:18:41 EET" name="submitOrder" finished-at="2025-04-22T02:18:46 EET" duration-ms="5405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- tests.SubmitOrderTest -->
      <class name="tests.AddProductToCartTest">
        <test-method signature="UserCanAddProductToCart()[pri:0, instance:tests.AddProductToCartTest@25bfcafd]" started-at="2025-04-22T02:18:25 EET" name="UserCanAddProductToCart" finished-at="2025-04-22T02:18:41 EET" duration-ms="16051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserCanAddProductToCart -->
      </class> <!-- tests.AddProductToCartTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
